#!/bin/sh

##############################################################################################
#
# POSIX-compliant Cloudflare DDNS updater script
#
# DISCLAIMER: A large portion of this code was generated by Claude Sonnet 4.6, with some
#             alterations by me. I wrote this for my own personal use so I could learn
#             more about shell scripting and it is only intended for my own personal use -
#             I cannot guarantee its reliability or security! I reccommend using something
#             created by actual smart people if you're looking for a DDNS solution
#             yourself, like one of the following:
#
#             - cloudflare-ddns: https://github.com/favonia/cloudflare-ddns
#             - ddclient:        https://github.com/ddclient/ddclient
#
##############################################################################################

# -e exits immediately if a command returns a non-zero exit code, -u treats unset variables as an error.
# || true bypasses -e!!! keep this in mind when reading!!! shell script is weird
set -eu

# -+ CONFIG +-

WORKING_DIR="/home/container/cf-ddns"
LOCK_DIR="$WORKING_DIR/cf-ddns.lock"
CACHE_FILE="$WORKING_DIR/ip-cache.txt"
SECRETS_FILE="$WORKING_DIR/secrets.env"
LOG_FILE="$WORKING_DIR/run.log"
LOG_MAX_LINES=1000

# -+ LOGGING FUNCTIONS +-

log() {
    msg="$(date '+%Y-%m-%d %H:%M:%S') $*"

    # Print to standard output (stdout)
    printf '%s\n' "$msg"

    # Append safely to tracking file
    printf '%s\n' "$msg" >> "$LOG_FILE"
}

log_err() {
    msg="$(date '+%Y-%m-%d %H:%M:%S') ERROR: $*"

    # Direct errors explicitly to standard error stream (stderr)
    printf '%s\n' "$msg" >&2

    # Mirror error context safely into tracking file
    printf '%s\n' "$msg" >> "$LOG_FILE"
}

trim_log() {
    # Stop execution of this function if no log file exists
    [ -f "$LOG_FILE" ] || return 0

    # Read the current number of lines in the log file
    lines=$(wc -l < "$LOG_FILE")

    # If the log exceeds the maximum allowed lines, trim it down to the last LOG_MAX_LINES lines
    if [ "$lines" -gt "$LOG_MAX_LINES" ]; then
        # Create the trimmed version completely safely under a temporary name
        tail -n "$LOG_MAX_LINES" "$LOG_FILE" > "$LOG_FILE.tmp"

        # Overwrite the original log file with the trimmed version. Using mv to do this means it should be impossible to have a partially written log file if the script is interrupted or crashes
        mv "$LOG_FILE.tmp" "$LOG_FILE"
    fi
}

# -+ LOCKING FUNCTION +-

mkdir -p "$WORKING_DIR"

# Try to create a lock directory and save any error output to a variable. If statement is executed if this fails.
if ! mklockdir_output=$(mkdir "$LOCK_DIR" 2>&1); then
    case "$mklockdir_output" in
    # If it already exists, it's likely due to another instance of the script running already.
    *'File exists'*)
        printf 'Error: Lock directory already exists. Another instance of this script is likely running already.\n' >&2
        exit 1
        ;;
    *)
    # Any other errors are not my problem lol (well they are but they're not something I can give much more context on)
        printf 'Error: Failed to create lock directory: %s\n' "$mklockdir_output" >&2
        exit 1
        ;;
    esac
fi

trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT INT TERM

# Clean up any leftover temporary files from a previous crashed run
rm -f "$LOG_FILE.tmp"

# -+ SOURCE SECRETS +-
if [ -f "$SECRETS_FILE" ]; then
    # Source the secrets/tokens needed to authenticate with the Cloudflare API
    . "$SECRETS_FILE"
else
    # Fail and exit if the file doesn't exist
    log_err "Secrets file missing. Please cp secrets.env.example to secrets.env and fill in the required values before running again."
    exit 1
fi


# -+ ONLINE IP CHECK FUNCTION +-

get_ip() {
    ip=$(curl -4fsS --max-time 15 https://ipv4.icanhazip.com 2>/dev/null || true)
    [ -n "$ip" ] || ip=$(curl -4fsS --max-time 15 https://api.ipify.org 2>/dev/null || true)

    ip=$(printf '%s' "$ip" | tr -d '\r\n')

    [ -n "$ip" ] || {
        log_err "Failed to determine public IP"
        exit 1
    }

    case "$ip" in
        *[!0-9.]*|'')
            log_err "Invalid IP format: $ip"
            exit 1
            ;;
        0.0.0.0|127.*|10.*|192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[0-1].*)
            log_err "Private/reserved IP rejected: $ip"
            exit 1
            ;;
    esac

    printf '%s\n' "$ip"
}

# -+ MAIN LOGIC +-

# Prune old logs right at the beginning of the run sequence
trim_log

PUBLIC_IP=$(get_ip)

# Check if the IP has been cached and exit without failing if it matches the IP fetched above
KNOWN_IP=""
[ -f "$CACHE_FILE" ] && KNOWN_IP=$(cat "$CACHE_FILE" 2>/dev/null || true)

if [ "$PUBLIC_IP" = "$KNOWN_IP" ]; then
    exit 0
fi

if [ -z "$KNOWN_IP" ]; then
    log "No cached IP found, assuming first run. Current IP: $PUBLIC_IP"
else
    log "IP change detected: $KNOWN_IP -> $PUBLIC_IP"
fi

# API request to update the DNS record with the new IP address
response=$(curl -4sS --max-time 15 -X PATCH \
    "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/$CF_RECORD_ID" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $CF_API_TOKEN" \
    -d "{\"content\":\"$PUBLIC_IP\"}" \
    -w "\n%{http_code}")

# Catch empty responses from the API
[ -n "$response" ] || {
    log_err "Cloudflare request failed"
    exit 1
}

# Separate the returned HTTP status code from the response body
code=$(printf '%s\n' "$response" | tail -n1)
body=$(printf '%s\n' "$response" | sed '$d')

# Check if the update was successful by looking for a 200 status code and a "success": true field in the response body.
if [ "$code" = "200" ] && printf '%s\n' "$body" | grep -q '"success"[[:space:]]*:[[:space:]]*true'; then

    # If successful, update the cache with the new public IP and log a successful run
    printf '%s\n' "$PUBLIC_IP" > "$CACHE_FILE"
    log "DNS updated successfully"
    
    # This is redundant but I like to be explicit about where my scripts end
    exit 0
else
    # If not, log an error and exit with an error code
    log_err "Cloudflare update failed (HTTP $code)"
    exit 1
fi